### PR TITLE
WIP Fix SwiftPM support

### PR DESCRIPTION
**Pull request by sam-w**
I think there's a lot more work to do until Swift Package Manager is successfully supported. Here's where I've gotten to so far. Swift PM is supported, but as you can see from the diff, there's only a subset of functionality currently working. I'll add some comments, and if anyone has the time to take this PR further I'd welcome contributions.

## Current state:
You can pull in the `task/spm-support` branch from my fork of this repo (https://github.com/LoungeBuddy/okta-oidc-ios) and successfully use the `OktaOidc` package ⚠️ **ONLY** ⚠️ if you are not relying on iOS or MacOS-specific functionality. This will not work if you are using `signInWithBrowser` and related functionality.

## Done:
- SwiftPM does not support targets with both Swift AND Objc sources. The simplest way to make this project work is to have the `AppAuth` target be Objc only, and the `OktaOidc` target be Swift only. [`OktaUserAgent` must therefore be moved from `OktaOidc` to `AppAuth`](https://github.com/okta/okta-oidc-ios/pull/245/commits/d9e18eb035e0bf0d4c2ce210fd050a084b080fe5).
- For ease of development, [I've reflected these changes ☝️ in the Xcode project too](https://github.com/okta/okta-oidc-ios/pull/245/commits/e57fbd6198c2e9056fec6f88f0ccbda8faf85a75)
- Now that we have multiple targets, we need to [import them to the right places](https://github.com/okta/okta-oidc-ios/pull/245/commits/d7a9914ca7c628fba01d9bbde596e4050229cf13); we need to [expose Objc headers to Swift](https://github.com/okta/okta-oidc-ios/pull/245/commits/dead88126efd11eddd9ffab1a3a90a3cd6b2e9db); and we need to [generate a modulemap for the `AppAuth` target](https://github.com/okta/okta-oidc-ios/pull/245/commits/492fa3445605f82b73bf1feddd6b0a3da69d2c59).

## TODO:
- If you `checkout` https://github.com/okta/okta-oidc-ios/pull/245/commits/492fa3445605f82b73bf1feddd6b0a3da69d2c59 and `swift build`, you'll see that SwiftPM can't import `UIKit` for the iOS-specific portions of the target:

```
In file included from /Volumes/Shared/CodeScratch/okta-oidc-ios/Okta/AppAuth/iOS/OIDExternalUserAgentIOS.m:21:
/Volumes/Shared/CodeScratch/okta-oidc-ios/Okta/AppAuth/iOS/OIDExternalUserAgentIOS.h:21:9: fatal error: 'UIKit/UIKit.h' file not found
In file included from /Volumes/Shared/CodeScratch/okta-oidc-ios/Okta/AppAuth/iOS/OIDExternalUserAgentNoSsoIOS.m:13:
/Volumes/Shared/CodeScratch/okta-oidc-ios/Okta/AppAuth/iOS/OIDExternalUserAgentNoSsoIOS.h:13:9: fatal error: 'UIKit/UIKit.h' file not found
#import <UIKit/UIKit.h>
        ^~~~~~~~~~~~~~~
```

I'm not sure how to get around this, so I've just [removed iOS-specific code from the target](https://github.com/okta/okta-oidc-ios/pull/245/commits/77b8ee0e18e4e0c4f44c5fc3476bfc25a7c1ab2f) for now.

### CODE REVIEW

**Comment by mikenachbaur-okta** [comment]
@sam-w Swift Package Manager support was introduced in #254 and is available in the 3.9.3 release. As such, I'll close this PR. If you have any problems with using SPM, please let us know.

**Comment by sam-w** [comment]
> @sam-w Swift Package Manager support was introduced in #254 and is available in the 3.9.3 release. As such, I'll close this PR. If you have any problems with using SPM, please let us know.

@mikenachbaur-okta thanks for the ping Mike! I'll switch back from my fork and let you know if I have any issues
